edited cloudbuild files
ortelius/store-frontend pull request #1
Opened 2022-03-08 17:38 UTC by Arvind644

2022-03-14 15:46 UTC, sbtaylor15 requested changes

2022-03-14 15:46 UTC, sbtaylor15 commented on component.toml
> +Name = "GLOBAL.ortelius.saas.frontend"
@Arvind644 
Wrong domain name.   It should be somewhere under the `GLOBAL.Santa Fe Software.Online Store Company.Hipster Store` domains.  Verify the domain by looking that the old service in the https://console.deployhub.com using the stella99 userid.

2022-03-17 11:34 UTC, Arvind644 commented on component.toml
> +Name = "GLOBAL.ortelius.saas.frontend"
I edited the name, please check it

2022-03-17 11:35 UTC, Arvind644 commented on component.toml
> +Name = "GLOBAL.ortelius.saas.frontend"
I edited the name, please check it

2022-03-17 15:58 UTC, merged